# Generated by Django 2.2.19 on 2021-04-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='title_en',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='title_ru',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='title_uz',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
