# Generated by Django 2.2.5 on 2021-04-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=700)),
                ('watch_count', models.PositiveIntegerField(default=0)),
                ('assessment_type', models.CharField(choices=[('TIMSS', 'TIMSS'), ('PISA', 'PISA'), ('PIRLS', 'PIRLS')], max_length=20)),
                ('video_type', models.CharField(choices=[('teachers', 'teachers'), ('students', 'students'), ('parents', 'parents')], max_length=20)),
                ('video', models.FileField(upload_to='publications/videos/')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
