# Generated by Django 2.2.5 on 2021-04-03 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('area', models.CharField(choices=[('', 'Hududingizni tanlang'), ('hudud1', 'hudud1'), ('hudud2', 'hudud2'), ('hudud3', 'hudud3')], max_length=50)),
                ('city', models.CharField(choices=[('', 'Shahar/tumaningizni tanlang'), ('Buxoro', 'Buxoro'), ('Toshkent', 'Toshkent'), ('Samarqand', 'Samarqand')], max_length=50)),
                ('school', models.CharField(choices=[('', 'Maktabingizni tanlang'), ('maktab1', 'maktab1'), ('maktab2', 'maktab2'), ('maktab3', 'maktab3')], max_length=50)),
                ('grade', models.CharField(choices=[('', 'Sinfingizni tanlang'), ('sinf1', 'sinf1'), ('sinf2', 'sinf2'), ('sinf3', 'sinf3')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
