# Generated by Django 2.2.5 on 2021-04-03 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilecreation',
            name='login',
        ),
    ]
