# Generated by Django 2.2.5 on 2021-04-03 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profilecreation_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecreation',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
