# Generated by Django 2.2.5 on 2021-04-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210403_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecreation',
            name='login',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
