# Generated by Django 2.2.5 on 2021-04-03 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210403_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilecreation',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
