# Generated by Django 2.2.5 on 2021-04-02 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Company Details', 'verbose_name_plural': 'Company Details'},
        ),
    ]
