# Generated by Django 2.2.5 on 2021-04-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20210402_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='company_description',
            field=models.TextField(max_length=3000),
        ),
    ]
