# Generated by Django 2.2.20 on 2021-04-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20210403_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='address_en',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='address_ru',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='address_uz',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='company_description_en',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='company_description_ru',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='company_description_uz',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
